vim.keymap.set('n', 'n', 'j')
vim.keymap.set('n', 'j', 'n')
vim.keymap.set('n', 'k', 'e')
vim.keymap.set('n', 'e', 'k')
vim.keymap.set('v', 'n', 'j')
vim.keymap.set('v', 'j', 'n')
vim.keymap.set('v', 'k', 'e')
vim.keymap.set('v', 'e', 'k')

vim.keymap.set('v', 'N', ":m '>+1<CR>gv=gv")
vim.keymap.set('v', 'E', ":m '<-2<CR>gv=gv")
vim.keymap.set('n', 'j', "nzzzv")
vim.keymap.set('n', 'J', "Nzzzv")

vim.keymap.set('n', 'm', 'h')
vim.keymap.set('n', 'h', 'm')
vim.keymap.set('v', 'm', 'h')
vim.keymap.set('v', 'h', 'm')

vim.keymap.set('n', 'i', 'l')
vim.keymap.set('n', 'l', 'i')
vim.keymap.set('v', 'i', 'l')
vim.keymap.set('v', 'l', 'i')
